version: '3.7'
services:
  nginx:
    image: nginx:latest
    ports:
      - "80:80"
    depends_on:
      - php
    volumes:
      - ./nginx-conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-conf/nginx.conf:/etc/nginx/nginx.conf
      - ./sites/otus-php:/var/www
      - ./logs:/var/log/nginx

  php:
    build: ./docker_images/php
    depends_on:
      - postgresql
      - rabbitmq
    volumes:
      - ./docker_images/php/40-custom.ini:/usr/local/etc/php/conf.d/40-custom.ini
      - ./sites/otus-php:/var/www

  rabbitmq:
    image: rabbitmq:management
    depends_on:
      - postgresql
    environment:
      - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
      - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
      - RABBITMQ_LOGS=${RABBITMQ_LOGS}
    ports:
      - "56721:5672"
      - "15672:15672"

  postgresql:
    image: postgres:latest
    ports:
      - "54320:5432"
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    shm_size: "1gb"
