version: '3.7'
services:
  nginx-balancer:
    image: nginx:latest
    ports:
      - "80:80"
    container_name: otus-nginx-hw6.2-balancer
    depends_on:
      - php-backend1
      - php-backend2
      - php-backend3
    volumes:
      - ./nginx-balancer-conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-balancer-conf/nginx.conf:/etc/nginx/nginx.conf
      - ./sites/otus-php:/var/www
      - ./sockets:/var/run
  nginx-backend1:
    image: nginx:latest
    ports:
      - "80:80"
    container_name: otus-nginx-hw6.2-backend1
    depends_on:
      - php-backend1
      - nginx-balancer
    volumes:
      - ./nginx-backend1-conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-backend1-conf/nginx.conf:/etc/nginx/nginx.conf
      - ./sites/otus-php:/var/www
      - ./sockets:/var/run
  nginx-backend2:
    image: nginx:latest
    ports:
      - "80:80"
    container_name: otus-nginx-hw6.2-backend2
    depends_on:
      - php-backend2
      - nginx-balancer
    volumes:
      - ./nginx-backend2-conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-backend2-conf/nginx.conf:/etc/nginx/nginx.conf
      - ./sites/otus-php:/var/www
      - ./sockets:/var/run
  nginx-backend3:
    image: nginx:latest
    ports:
      - "80:80"
    container_name: otus-nginx-hw6.2-backend3
    depends_on:
      - php-backend3
      - nginx-balancer
    volumes:
      - ./nginx-backend3-conf/conf.d/default.conf:/etc/nginx/conf.d/default.conf
      - ./nginx-backend3-conf/nginx.conf:/etc/nginx/nginx.conf
      - ./sites/otus-php:/var/www
      - ./sockets:/var/run
  php-backend1:
    build: ./docker_images/php
    volumes:
      - ./php-backend1-conf/40-custom.ini:/usr/local/etc/php/conf.d/40-custom.ini
      - ./php-backend1-conf/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./sites/otus-php:/var/www
      - ./sockets:/var/run
    container_name: otus-php-backend1-hw6.2
  php-backend2:
    build: ./docker_images/php
    volumes:
      - ./php-backend2-conf/40-custom.ini:/usr/local/etc/php/conf.d/40-custom.ini
      - ./php-backend2-conf/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./sites/otus-php:/var/www
      - ./sockets:/var/run
    container_name: otus-php-backend2-hw6.2
  php-backend3:
    build: ./docker_images/php
    volumes:
      - ./php-backend3-conf/40-custom.ini:/usr/local/etc/php/conf.d/40-custom.ini
      - ./php-backend3-conf/zz-docker.conf:/usr/local/etc/php-fpm.d/zz-docker.conf
      - ./sites/otus-php:/var/www
      - ./sockets:/var/run
    container_name: otus-php-backend3-hw6.2


