version: '3.7'
services:
  postgresql-hw10-t1:
    image: postgres:latest
    ports:
      - 54320:5432
    volumes:
      - ./docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
      - ./some_scripts:/some_scripts
    environment:
      POSTGRES_PASSWORD: 'password'
    shm_size: '1gb'
    command: "postgres -c 'shared_buffers=1GB' -c 'work_mem=150MB'"